### ISSUE TITLE
Make Vehicle Doctype a simple (master) doctype.

### ISSUE THREAD

**Issue by gaurav-naik** [gaurav-naik/andesit_karang_anyar#13]
Vehicle Doctype is currently implemented as a child doctype.
In the final app, it will be implemented as a master doctype.

**Comment by saidsl** [comment]
A few issues
1. Please check the Vehicle DocType page, I am trying to check it and it initially loads but then blanks out. See screen grab
2. Please make the Vehicle Registration Number Unique & Set Only Once

![screen shot 2016-06-23 at 1 22 40 pm](https://cloud.githubusercontent.com/assets/5009367/16292598/9b67465a-3945-11e6-9010-ca5491bd06c6.png)
