### ISSUE TITLE
Tare Weight Inclusion & Implementation

### ISSUE THREAD

**Issue by saidsl** [gaurav-naik/andesit_karang_anyar#14]
Based on the initial scope, the tare weight was to be obtained from the entered value in the Vehicle DocType, however, due to conditions on the site/field, this approach is subject to abuse, therefore, Tare Weight must now be obtained in the First or Second weighing depending on whether its an incoming or outgoing load.

Incoming Load = First Weighing --> Gross Weight
Incoming Load = Second Weighing --> Tare Weight
Result = GW - TW = Nett Weight
Nett Weight is what must match with the Qty in the Purchase order.

Outgoing Load = First Weighing --> Tare Weight
Outgoing Load = Second Weighing --> Gross Weight
Result = TW - GW = Nett Weight
Nett Weight is what must match with the Qty in the Sales Order.

We will retain the Tare Weight field in the Vehicle Doctype for Comparison and use it to validate the Vehicles.

**Comment by revant** [comment]
@vishdha

Now that the Weigh Bridge Ticket is auto fetching Tare Weight when the Vehicle is selected. (https://github.com/gaurav-naik/andesit_karang_anyar/commit/41537c73ed307717ee290545b93024c05e2d25cf)
Write a call under validate in Vehicle such that : 

 - If Customer is selected:
	- First Weighing --> Gross Weight
	- Second Weighing --> Tare Weight
	- Compare Second Weighing with Vehicle Tare Weight with + or - 10% allowable difference and show a msgprint(_("Tare Weight Mismatch"))

- If Supplier is selected:
	- First Weighing --> Tare Weight
	- Second Weighing --> Gross Weight
	- Compare First Weighing with Vehicle Tare Weight with + or - 10% allowable difference and show a msgprint(_("Tare Weight Mismatch"))

**Comment by saidsl** [comment]
Correction in Gross/Tare Weight

If Customer is selected
First Weighing —> Tare Weight, since its empty and should be cross checked with entered Tare Weight with 10% Tolerance and show message Tare Weight Mismatch
Second Weighing —> Gross Weight, since now it loaded
Compare both Weighings: Tare — Gross Weight = Nett Weight
If Supplier is Selected
First Weighing —> Gross Weight, as its loaded with raw material
Second Weight —> Tare Weight, as its now empty nd should be cross checked with entered Tare Weight with 10% Tolerance and show message Tare Weight Mismatch
Compare both Weighings: Gross Weigh — Tare Weight = Nett Weight

Hope this clarifies the Order/Sequence/Process


On 25 Jun 2016, at 1:57 PM, Revant Nandgaonkar <notifications@github.com> wrote:

@vishdha <https://github.com/vishdha>
Now that the Weigh Bridge Ticket is auto fetching Tare Weight when the Vehicle is selected. (41537c7 <https://github.com/gaurav-naik/andesit_karang_anyar/commit/41537c73ed307717ee290545b93024c05e2d25cf>)
Write a call under validate in Vehicle such that :

If Customer is selected:
First Weighing --> Gross Weight
Second Weighing --> Tare Weight
Compare Second Weighing with Vehicle Tare Weight with + or - 10% allowable difference and show a msgprint(_("Tare Weight Mismatch"))
If Supplier is selected:
First Weighing --> Tare Weight
Second Weighing --> Gross Weight
Compare First Weighing with Vehicle Tare Weight with + or - 10% allowable difference and show a msgprint(_("Tare Weight Mismatch"))
