### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by saidsl** [gaurav-naik/andesit_karang_anyar#27]
One of the items that was requested in the initial Brief was the need to create some custom scripted reports. The most immediate being

1. Purchase Order & Sales Order -- **Total Row**. Seems this is an issue with ERPNext and there is no resolution in the Forum how best to resolve
2. WBT -- **Total Row**. Same as above needs total row for Nett Weight

I will add to this list in the coming days,

Thanks Said

**Comment by gaurav-naik** [comment]
@saidsl 

Hello.

Reports for Sales and Purchase Order and Weighbridge Ticket with basic filtering have been added. They also have total rows. 
Pl. let us know if these fit the requirement, or if any changes are required.

**Comment by saidsl** [comment]
Hi Gaurav,

Can we please create an additional link for each SO & PO under its respective Module, so that it can also be accessed from there under Custom Reports.

Other than that, its all good.

Regards
Said





On 12 Jul 2016, at 6:34 PM, gaurav-naik <notifications@github.com> wrote:

@saidsl <https://github.com/saidsl>
Hello.

Reports for Sales and Purchase Order and Weighbridge Ticket with basic filtering have been added. They also have total rows. 
Pl. let us know if these fit the requirement, or if any changes are required.

**Comment by gaurav-naik** [comment]
Would the 'Add to Desktop' feature be an acceptable alternative to this?

![addtodesktop](https://cloud.githubusercontent.com/assets/17795124/16940419/61fc82ce-4da7-11e6-92b5-3d84feaab108.png)

**Click on the 'Add to Desktop' item.**

![addtodesktop_2](https://cloud.githubusercontent.com/assets/17795124/16940440/84e13a00-4da7-11e6-8c43-c33332934e2e.png)

**Notice the 'Sales and Purchase Order Report' desktop icon next to Learn.**

The desktop icon will not be visible on the desktops of other Users. 
Optionally, the link for this report under AKA Weighbridge Ticket Management can be hidden.

**Comment by saidsl** [comment]
Unfortunately, that would not be an alternative, Where is the issue with including it in the each respective section. Usually when I create a report using the Report Module and we can specify if we wanted to make it a custom report and add it to the section

Regards
Said




On 19 Jul 2016, at 3:29 PM, gaurav-naik <notifications@github.com> wrote:

Would the 'Add to Desktop' feature be an acceptable alternative to this?

 <https://cloud.githubusercontent.com/assets/17795124/16940419/61fc82ce-4da7-11e6-92b5-3d84feaab108.png>
Click on the 'Add to Desktop' item.

 <https://cloud.githubusercontent.com/assets/17795124/16940440/84e13a00-4da7-11e6-8c43-c33332934e2e.png>
Notice the 'Sales and Purchase Order Report' desktop icon next to Learn.

The desktop icon will not be visible on the desktops of other Users. 
Optionally, the link for this report under AKA Weighbridge Ticket Management can be hidden.

**Comment by gaurav-naik** [comment]
@saidsl 

As the Sales Order and Puchase Order report displays both SO's and PO's, it needs to be linked with both Buying and Selling modules. In case of other custom reports, even if they are query reports, they are usually linked with one module. 

The report can now be opened from both Selling and Buying modules, under Custom Reports.

Pl. let me know if this is suitable.

https://github.com/gaurav-naik/andesit_karang_anyar/commit/50f73a0238da5536c6484c484506d2c1dd468941

**Comment by saidsl** [comment]
Gaurav,

That’s fine what you have done. All good Thanks

Regards
Said


On 19 Jul 2016, at 10:06 PM, gaurav-naik <notifications@github.com> wrote:

@saidsl <https://github.com/saidsl>
As the Sales Order and Puchase Order report displays both SO's and PO's, it needs to be linked with both Buying and Selling modules. In case of other custom reports, even if they are query reports, they are usually linked with one module.

The report can now be opened from both Selling and Buying modules, under Custom Reports.

Pl. let me know if this is suitable.

50f73a0 <https://github.com/gaurav-naik/andesit_karang_anyar/commit/50f73a0238da5536c6484c484506d2c1dd468941>
