### ISSUE TITLE
Licence must be validated to have 12 digits

### ISSUE THREAD

**Issue by niharRaut** [gaurav-naik/andesit_karang_anyar#3]
Client side + server side validation  
**ETA :** 0.75 hours.

**Comment by saidsl** [comment]
Please ensure that, if no License Number is entered that the notification comes up while the pop-up/modal is active and not during Save.

As it is not, when an incorrect License is entered, the Save Button only dims out and does not provide any clue as to what's happening

**Comment by gaurav-naik** [comment]
Licence No is now a mandatory field which accepts a maximum of 12 characters as input. 

If the licence no is less than 12 characters and user moves to another field, a message will pop up saying that the input is too short. Additionally, a server-side validation will ensure that the document does not save if the input value is less than 12 characters, with the appropriate message.

**Comment by saidsl** [comment]
@gaurav-naik 
Where is this being implemented? on http://test.andesitkaranganyar.com/ or locally?

**Comment by gaurav-naik** [comment]
@saidsl 
Changes have been made locally.

As soon as they have been tested, I will release them on the repository gaurav-naik/andesit_karang_anyar and let you know.

Is there a separate local machine on which you can view the changes? We would like to retain test.andesitkaranganyar.com for reference.
