### ISSUE TITLE
Replicate 'Print Without Amount' feature of Delivery Note in Purchase Receipt Doctype

### ISSUE THREAD

**Issue by gaurav-naik** [gaurav-naik/andesit_karang_anyar#31]
1. Add custom field 'Print Without Amount', type 'Check'. Must be checked by default. Value should be 1 or true.
	
2. Add custom script. 
	In handler for refresh event, set the 'print_hide' property to True for fields associated with amount in Purchase Receipt and Purchase Receipt Item

Developer Notes:

1. Check behaviour of original feature in Delivery Note. 
	Create a delivery note and save it. Click on the print icon before and after checking Print Without Amount field to true. (Printing Details section)  

2. Refer to the function 'before_print' in delivery_note.py (Line 64) to see which fields to hide.

3. Fields to be hidden via custom script. 
	Use the set_df_property() method.
	Refer to weighbridge_ticket.js

**Comment by gaurav-naik** [comment]
@saidsl

Hi Said.

The custom script approach hasn't worked as expected. The Print without Amount feature cannot be replicated using simple client-side functions (javascript) and replicating the before_print function on the server-side is a difficult task to complete within a realistic time frame.

I recommend we use the custom Print Format alternative you suggested under issue #23. Is that ok?

**Comment by saidsl** [comment]
Hi Gaurav

Yes, if the print option is the easier, faster and more reliable approach to take, that’s fine. Please proceed with it.

Regards
Said


On 15 Jul 2016, at 12:09 AM, gaurav-naik <notifications@github.com> wrote:

@saidsl <https://github.com/saidsl>
Hi Said.

The custom script approach hasn't worked as expected. The Print without Amount feature cannot be replicated using simple client-side functions (javascript) and replicating the before_print function on the server-side is a difficult task to complete within a realistic time frame.

I recommend we use the custom Print Format alternative you suggested under issue #23 <https://github.com/gaurav-naik/andesit_karang_anyar/issues/23>. Is that ok?

**Comment by gaurav-naik** [comment]
@saidsl 

Hi Said.

'Print without Amount' is now the default print format for Purchase Receipt. The standard print format is also available for selection in print mode.
